version: "3.5"
services:
  dashboard:
      image: grafana/grafana-enterprise
      ports:
      - "1234:3000"
      restart: always
      volumes:
      - grafana:/var/lib/grafana
      networks:
        - some-net

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.4
    container_name: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
      - influxdbConfig:/root/.influxdbv2
    ports:
      - "8086:8086"
    networks:
        - some-net

  influxdb_cli:
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.4
    entrypoint: influx setup --bucket test_bucket -t test_token -o test_org --username=test_username --password=test_password --host=http://influxdb:8086 -f
    networks:
        - some-net
    restart: on-failure:20
    depends_on:
      - influxdb
      
volumes:
  influxdb:
  influxdbConfig:
  grafana:

networks:
  some-net:
    driver: bridge
