version: "3.5"
services:
  dashboard:
      image: grafana/grafana-enterprise
      ports:
      - "1234:3000"
      restart: always
      volumes:
      - grafana:/var/lib/grafana
      networks:
        - some-net
      
  influx:
      image: influxdb
      ports:
        - 8086:8086
      volumes:
        - influxdb:/data/db
      networks:
        - some-net
volumes:
  influxdb:
  grafana:

networks:
  some-net:
    driver: bridge
