version: "3.5"
services:
  dashboard:
      image: grafana/grafana-enterprise
      ports:
      - "1234:3000"
      restart: always
      volumes:
      - grafana:/var/lib/grafana
      networks:
        - some-net

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheusdb:/prometheus
    ports:
      - "9000:9090"
    networks:
        - some-net
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheusdb:
  grafana:

networks:
  some-net:
    driver: bridge
