version: "3.5"
services:
  dashboard:
      image: grafana/grafana-enterprise
      ports:
      - "3000:3000"
      restart: always
      volumes:
      - grafana:/var/lib/grafana
      
  mongo:
      image: mongo
      ports:
        - 9087:27017
      volumes:
        - mongodb:/data/db
      networks:
        - some-net
volumes:
  mongodb:
  grafana:

networks:
  some-net:
    driver: bridge
