global:
  scrape_interval: 2s
  scrape_timeout: 1s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'network-monitor:7896'